### ISSUE TITLE
Add a "report problems" feedback form

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/UK-Polling-Stations#139] opened 2016-02-05 10:34 UTC
From @chris48s: 

> Each /postcode/ page should have a 'report an issue with this page' button on it which takes the user to the form where they can:
> - request removal of a boundary
> - request removal of a polling station
> - submit a corrected address for a polling station
> - provide a contact email address?
>   Submitting that form inserts a record (and probably fires off an email to alert an administrator).
>   There is a corresponding page (admin interface is probably the sensible place for this) where an admin can review these requests and either apply the correction or ignore the request if it appears spurious/invalid.

**Comment by symroe** [comment] 2016-02-05 10:35
Let's have a conversation about this before carring on – we need to find out more from councils about what they actually want.

**Comment by chris48s** [comment] 2016-02-06 15:54
Sounds reasonable.
Btw, is this issue now a duplicate of #131, or are they subtly different?

**Comment by symroe** [comment] 2016-02-10 13:52
I think this is more about us hearing about any problem, whereas the other is about an easy way to remove data from the live site (including cache invalidation, and so on)

**Comment by chris48s** [comment] 2017-11-24 16:48
https://democracyclub.org.uk/blog/2017/10/20/where-do-i-vote-tour/

**Comment by chris48s** [comment] 2017-12-04 11:14
![](https://github.trello.services/images/mini-trello-icon.png) [WhereDIV: "report a problem" button](https://trello.com/c/nWmHuJjq/242-wherediv-report-a-problem-button)

**Comment by chris48s** [comment] 2018-02-09 18:02
Issues we need to solve:

1. Bug reports and feedback are mixed together
2. Extracting/triaging data is cumbersome + potentially error prone
   (psql on local machine to remote server + dump table)
3. Triage is cumbersome


## Form design

- How do you present 'bug report' and 'provide feedback'?
  - 2 forms (this will be confusing/ugly)
  - Have a single 'contact' form with 2 'user journeys':

> I want to...
>   - Provide feedback ---> "did you find this helpful?"
>   - Report a problem ---> "what sort of problem?"

- Once the form becomes more complex, how should we present it?
- Inline with JS show/hide the paths (how do we 'progressively enhance' this?)
- Seperate 'contact us' interaction with more of a 'wizard' workflow?

## Data Model

- Even if 'feedback' and 'report a problem' are one form, they should probably be 2 back-end tables
- Bug reports model lives in the logger DB
- Fields:
  - Source URL/slug/postcode
  - open/resolved flag
  - open text comment
  - source (WhereDIV/API consumer)
  - optional email address for follow-up
  - report type - enum:
    - polling location info is wrong
    - something else
    - Do we want an option for 'address is right but map is wrong'? It is a common class of error, but...
      - How do we express that clearly?
      - What if we didn't show a map?
      - What about third party sites?

## Information about the bug report

- If our form is inline, we can easily include the target postcode/address slug in the bug report
- If it is not, we need to pass that info into the form view (URL param/session data)
- If we have 3rd party users implement the form, we need to also have them pass in the target postcode/address slug - what is a slick way to do this? (not needed for MVP but should think about it) I reckon best plan = serve up a pre-populated 'bug report' url in the API JSON for each result.

## Admin interface

- Re-enable admin to provide interface to bug reports
- Useful thing to do because it also gives us a better way to manage API keys
- Need to enable sticky sessions on the load balancer (at the moment we don't do this)
- Need to set secret key in deploy repo if we are having sessions and admin accounts
- What's the MVP for bug reports?
  - Mark as resolved (make sure it is easy to do lots - tickbox, not button)
  - CSV download everything that is not marked as done sorted by issue type
- You can iterate from there. e.g: 'status' might be nice, but we don't _need_ it
- Admin interface should only talk to logger models

**Comment by chris48s** [comment] 2018-02-10 20:06
> Need to enable sticky sessions on the load balancer (at the moment we don't do this)

Maybe other alternatives to this would be to store the session data in redis or the logger DB.

**Comment by symroe** [comment] 2018-02-10 23:14
Really sticky sessions, on Who we're using signed cookies for storage,
simplify everything. Might be good here?

**Comment by chris48s** [comment] 2018-02-12 11:16
`SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"`
https://docs.djangoproject.com/en/2.0/topics/http/sessions/#using-cookie-based-sessions

**Comment by chris48s** [comment] 2018-02-13 10:18
Also, improve tooling for extracting negative feedback comments. Even with a great user journey it is unrealistic that expect that we won't receive any errors reported this way.

**Closed** 2018-03-27 13:33 UTC
