### ISSUE TITLE
Import GRA-Gravesham Borough Council for 2024-05-02

### ISSUE THREAD

**Issue by polling-bot-4000** [DemocracyClub/UK-Polling-Stations#6105] opened 2024-02-01 15:10 UTC
EMS: unknown
Files:
- `GRA/2024-05-02/2024-02-01T15:10:02.515725/PollingStationsInUseAtAnElection_2024-02-01 15-07.csv`

**Comment by GeoWill** [comment] 2024-02-27 18:09
Dupe of https://github.com/DemocracyClub/UK-Polling-Stations/issues/6237

**Closed by GeoWill** 2024-02-27 18:09 UTC
Labels: Data Import, ready
