### ISSUE TITLE
Why don't we know where Phil should vote? 

### ISSUE THREAD

**Issue by davidmiller** [DemocracyClub/UK-Polling-Stations#102] opened 2015-04-15 14:57 UTC
The relevant postcode is RG1 41LR
The relevant polling station is The Scout Hut Poplar Place Newbury RG14 1NA

But we don't know that !

http://pollingstations.democracyclub.org.uk/postcode/RG141LR/

c.f. This conversation: 
https://twitter.com/PhilRumens/status/588347837328576512

**Comment by PhilRumens** [comment] 2015-04-27 09:24
There's another one of these here with a slightly different problem

http://pollingstations.democracyclub.org.uk/postcode/RG183BA/

**Comment by symroe** [comment] 2015-04-27 11:28
Turns out the first problem was a deployment issue.

As for `RG183BA` – looks like there isn't a polling station in that district?  Is that right?

**Comment by symroe** [comment] 2015-04-27 11:53
Update on this – I think the underlying data is actually missing – I really can't think of another reason...

See this screenshot:

![screen shot 2015-04-27 at 12 51 08](https://cloud.githubusercontent.com/assets/242329/7347030/3bb6bed6-ecdc-11e4-986d-9c38ac82a141.png)


Using an online tool to look at the shapefile, it's got red dots on for some reason – I have no idea what this means, but it's clearly an outlier in the data:

![screen shot 2015-04-27 at 12 52 31](https://cloud.githubusercontent.com/assets/242329/7347045/5fa8e918-ecdc-11e4-874b-a821c7aa7ba1.png)

@PhilRumens could you talk to your GIS person to make double sure it's ok?  It still could be our fault, but I really don't understand why!

**Comment by symroe** [comment] 2015-04-27 12:05
Confirmed that data is there, sorry @PhilRumens.  It's obviously a bug our end.

**Comment by symroe** [comment] 2015-04-27 12:21
Progress!  Turns out the `object_id` is the same as the polling district directly south of this one, meaning we're replacing it internally on import.

Both the IDs are `107`.  @PhilRumens, is this correct, or is there an error in the data?  I'll change the importer to import them both anyway, but it's a bit odd that there are duplicate IDs in the data.

**Comment by PhilRumens** [comment] 2015-04-27 12:36
I've asked our GIS team, will let you know what they say.

**Comment by symroe** [comment] 2015-04-27 12:49
Marking this as fixed now, as every postcode I tried is working.  I've started using a different ID field, the one that in this case is `NB8`

**Closed by symroe** 2015-04-27 12:49 UTC
Labels: in progress

**Comment by PhilRumens** [comment] 2015-04-27 12:56
RG141LR is fixed :+1: 

Still not seeing a polling station in:
http://pollingstations.democracyclub.org.uk/postcode/RG183BA/

**Comment by symroe** [comment] 2015-04-27 13:00
I'll make a new issue for that one – I think it's a different problem
